# Generated by Django 5.2.17 on 2026-09-30 10:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adres e-mail')),
                ('first_name', models.CharField(max_length=150, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nazwisko')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywne konto')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Dostęp do panelu admina')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dołączenia')),
                ('last_active_at', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia aktywność')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('secretariat', 'Sekretariat'), ('teacher', 'Nauczyciel'), ('homeroom_teacher', 'Wychowawca'), ('principal', 'Dyrekcja'), ('admin', 'Administrator')], max_length=20, verbose_name='Rola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.school', verbose_name='Szkoła')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Członkostwo w szkole',
                'verbose_name_plural': 'Członkostwa w szkołach',
                'constraints': [models.UniqueConstraint(fields=('user', 'school'), name='unique_user_school_membership')],
            },
        ),
    ]
