# Generated by Django 5.2.17 on 2026-09-29 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa Szkoły')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('rspo', models.CharField(blank=True, max_length=8, verbose_name='Numer RSPO')),
                ('regon', models.CharField(blank=True, max_length=14, verbose_name='Numer Regon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Szkoła',
                'verbose_name_plural': 'Szkoły',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=9, verbose_name='Rok Szkolny')),
                ('start_date', models.DateField(verbose_name='Data Rozpoczęcia')),
                ('end_date', models.DateField(verbose_name='Data zakończenia')),
                ('is_current', models.BooleanField(default=False, verbose_name='Bieżący rok')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.school')),
            ],
            options={
                'verbose_name': 'Rok Szkolny',
                'verbose_name_plural': 'Lata Szkolne',
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='Nazwa Klasy')),
                ('level', models.IntegerField(verbose_name='Poziom')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='core.school')),
            ],
            options={
                'verbose_name': 'Klasa',
                'verbose_name_plural': 'Klasy',
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='unique_class_per_year')],
            },
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_academic_year'),
        ),
    ]
