# Generated by Django 5.2.17 on 2026-10-06 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Tworzenie'), ('update', 'Edycja'), ('delete', 'Usuwanie'), ('login', 'Logowanie')], max_length=20, verbose_name='Operacja')),
                ('target_type', models.CharField(max_length=100, verbose_name='Typ obiektu')),
                ('target_id', models.CharField(max_length=255, verbose_name='Identyfikator obiektu')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Bezpieczny opis zmian')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Czas zdarzenia')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Aktor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.school', verbose_name='Szkoła')),
            ],
            options={
                'verbose_name': 'Wpis audytowy',
                'verbose_name_plural': 'Wpisy audytowe',
                'ordering': ['-created_at'],
            },
        ),
    ]
