# Generated by Django 5.2.17 on 2026-10-07 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
        ('students', '0002_remove_studentguardian_guardian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_cohorts', to='students.teacher', verbose_name='Wychowawca klasy'),
        ),
    ]
