# Generated by Django 5.2.17 on 2026-10-07 09:46

import apps.students.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Numer telefonu')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Adres e-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='core.school', verbose_name='Szkoła')),
                ('user', models.OneToOneField(blank=True, help_text='Konto użytkownika w systemie (opcjonalne)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opiekun',
                'verbose_name_plural': 'Opiekunowie',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('second_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Drugie imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('date_of_birth', models.DateField(verbose_name='Data urodzenia')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='Miejsce urodzenia')),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, validators=[apps.students.validators.validate_pesel], verbose_name='Numer PESEL')),
                ('id_document_type', models.CharField(blank=True, choices=[('PASSPORT', 'Paszport'), ('ID_CARD', 'Dowód osobisty'), ('OTHER', 'Inny dokument tożsamości')], default='', max_length=20, verbose_name='Rodzaj dokumentu tożsamości')),
                ('id_document_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Numer dokumentu tożsamości')),
                ('register_number', models.CharField(help_text='Numer ewidencyjny w księdze uczniów danej szkoły', max_length=50, verbose_name='Numer w księdze uczniów')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school', verbose_name='Szkoła')),
            ],
            options={
                'verbose_name': 'Uczeń',
                'verbose_name_plural': 'Uczniowie',
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('MOTHER', 'Matka'), ('FATHER', 'Ojciec'), ('LEGAL_GUARDIAN', 'Opiekun prawny'), ('OTHER', 'Inny')], default='LEGAL_GUARDIAN', max_length=20, verbose_name='Stopień pokrewieństwa / rola')),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Oznaczenie osoby jako pierwszego kontaktu w sprawach nagłych', verbose_name='Główny kontakt')),
                ('has_legal_custody', models.BooleanField(default=True, help_text='Wskazuje, czy opiekun posiada pełnię praw rodzicielskich/prawnych', verbose_name='Prawo do opieki prawnej')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Relacja Uczeń-Opiekun',
                'verbose_name_plural': 'Relacje Uczeń-Opiekun',
            },
        ),
        migrations.AddField(
            model_name='guardian',
            name='students',
            field=models.ManyToManyField(related_name='guardians', through='students.StudentGuardian', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'register_number'), name='unique_student_register_number_per_school'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('pesel__isnull', False)), fields=('school', 'pesel'), name='unique_student_pesel_per_school'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='unique_student_guardian_relationship'),
        ),
    ]
