# Generated by Django 5.2.17 on 2026-10-07 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentguardian',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='studentguardian',
            name='student',
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='np. 4A, I B', max_length=20, verbose_name='Nazwa klasy')),
                ('academic_year', models.CharField(help_text='np. 2025/2026', max_length=9, verbose_name='Rok szkolny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school', verbose_name='Szkoła')),
            ],
            options={
                'verbose_name': 'Klasa',
                'verbose_name_plural': 'Klasy',
                'ordering': ['school', '-academic_year', 'name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.schoolclass', verbose_name='Klasa'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_title', models.CharField(blank=True, default='', help_text='np. mgr, dr, mgr inż.', max_length=30, verbose_name='Tytuł / Tytuł zawodowy')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.school', verbose_name='Szkoła')),
                ('user', models.OneToOneField(blank=True, help_text='Konto użytkownika w systemie (opcjonalne)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Konto użytkownika')),
            ],
            options={
                'verbose_name': 'Nauczyciel',
                'verbose_name_plural': 'Nauczyciele',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_classes', to='students.teacher', verbose_name='Wychowawca klasy'),
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='StudentGuardian',
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('school', 'name', 'academic_year'), name='unique_class_name_per_school_and_year'),
        ),
    ]
