# Generated by Django 5.2.17 on 2026-10-07 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cohort_class_teacher'),
        ('students', '0002_remove_studentguardian_guardian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school_class',
        ),
        migrations.AddField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.cohort', verbose_name='Klasa'),
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
