# Generated by Django 5.2.17 on 2026-10-07 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cohort_class_teacher'),
        ('students', '0003_remove_student_school_class_student_cohort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Uczęszcza (Aktywny)'), ('GRADUATED', 'Absolwent (Ukończył szkołę)'), ('WITHDRAWN', 'Odszedł / Skreślony')], default='ACTIVE', max_length=20, verbose_name='Status ucznia'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.cohort', verbose_name='Obecna klasa'),
        ),
        migrations.CreateModel(
            name='StudentHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ADMISSION', 'Przyjęcie do szkoły'), ('CLASS_ASSIGNMENT', 'Przypisanie do klasy'), ('PROMOTION', 'Promocja do następnej klasy'), ('REPEAT', 'Powtarzanie klasy'), ('TRANSFER', 'Przeniesienie do innej klasy'), ('GRADUATION', 'Ukończenie szkoły'), ('WITHDRAWAL', 'Odejście ze szkoły')], max_length=30, verbose_name='Typ zdarzenia')),
                ('event_date', models.DateField(verbose_name='Data zdarzenia')),
                ('document_number', models.CharField(blank=True, default='', help_text='np. numer uchwały Rady Pedagogicznej', max_length=100, verbose_name='Numer uchwały / decyzji')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_history_entries', to='core.academicyear', verbose_name='Rok szkolny')),
                ('source_cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_source_entries', to='core.cohort', verbose_name='Klasa źródłowa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='students.student', verbose_name='Uczeń')),
                ('target_cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_target_entries', to='core.cohort', verbose_name='Klasa docelowa')),
            ],
            options={
                'verbose_name': 'Wpis w historii przebiegu nauki',
                'verbose_name_plural': 'Historia przebiegu nauki',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
