# Generated by Django 5.2.17 on 2026-10-09 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_status_alter_student_cohort_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDataCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Wyjaśnienie przyczyny zmiany istotnych danych (np. sprostowanie błędu pisarskiego, zmiana nazwiska po orzeczeniu)', verbose_name='Powód korekty')),
                ('changed_fields', models.JSONField(default=dict, help_text="Słownik reprezentujący różnice w postaci: {'field_name': {'old': ..., 'new': ...}}", verbose_name='Zmienione pola')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Czas korekty')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor korekty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_corrections', to='students.student', verbose_name='Uczeń')),
            ],
            options={
                'verbose_name': 'Korekta danych ucznia',
                'verbose_name_plural': 'Korekty danych uczniów',
                'ordering': ['-created_at'],
            },
        ),
    ]
